# Generated by Django 4.2 on 2023-06-22 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensor',
            old_name='discription',
            new_name='description',
        ),
    ]
