# Generated by Django 4.2 on 2023-06-23 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0005_rename_sensor_id_measurement_sensor'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='count',
            field=models.FloatField(null=True),
        ),
    ]
