version: '3'

services:

  migrate:
    build: .
    container_name: 'migrate'
    tty: true
    command: >
      /bin/sh -c "python3 manage.py migrate --force-color -v 3
      && python3 manage.py runserver 0.0.0.0:8000"
    environment:
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_PASSWORD=admin
      - DJANGO_SUPERUSER_EMAIL=admin@example.com
    volumes:
      - .:/measurement
    ports:
          - 8000:8000

  