# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение датчиков
GET {{baseUrl}}/sensors/
Content-Type: application/json

###

# создание датчика
POST {{baseUrl}}/sensors/
Content-Type: application/json

{ 
  "name": "ESP32",
  "description": "Датчик в комнате за холодильником"
}

###

# обновление датчика
PATCH {{baseUrl}}/sensors/18/
Content-Type: application/json

{
  "description": "Перенес датчик на бетон"
}

###

# добавление измерения
POST {{baseUrl}}/measurements/
Content-Type: application/json

{
  "sensor": 17,
  "temperature": 22.3
}

###

# получение информации по датчику
GET {{baseUrl}}/sensors/17/
Content-Type: application/json
